import type { PostDoc } from "./academy";

// Two published, fully-written articles. Six further topics seeded as
// drafts with real outlines — they must be reviewed before publishing.

const now = new Date().toISOString();

export const seedPosts: PostDoc[] = [
  {
    id: "post_start_online",
    slug: "how-to-start-learning-quran-online",
    title: { en: "How to Start Learning the Quran Online", ar: "كيف تبدأ تعلم القرآن أونلاين" },
    excerpt: {
      en: "A practical first-week guide: setting goals, preparing your space, and what to expect from your assessment.",
      ar: "دليل عملي للأسبوع الأول: تحديد الأهداف وتجهيز مكانك وما تتوقعه من جلسة التقييم.",
    },
    content: {
      en: "Starting to learn the Quran online is simpler than most people expect.\n\nFirst, clarify your goal. Do you want to read fluently, improve your Tajweed, memorize, or understand meanings? A clear goal helps your teacher choose the right starting point.\n\nSecond, prepare a quiet corner with a device, a camera, and a stable connection. Keep a notebook beside you — writing new letters and rules by hand speeds up learning.\n\nThird, book a free assessment. A short conversation about your level and schedule is enough to place you correctly. Expect to read a few lines so the teacher can hear your current level.\n\nFinally, protect a small daily habit. Fifteen focused minutes of revision every day beats a long session once a week. Consistency is the real curriculum.",
      ar: "بدء تعلم القرآن أونلاين أبسط مما يتوقع معظم الناس.\n\nأولًا، حدد هدفك: هل تريد القراءة بطلاقة، أم تحسين التجويد، أم الحفظ، أم فهم المعاني؟ الهدف الواضح يساعد معلمك على اختيار نقطة البداية الصحيحة.\n\nثانيًا، جهّز ركنًا هادئًا بجهاز وكاميرا واتصال مستقر، وضع دفترًا بجانبك — كتابة الحروف والقواعد الجديدة باليد تسرّع التعلم.\n\nثالثًا، احجز جلسة تقييم مجانية. محادثة قصيرة عن مستواك ومواعيدك تكفي لوضعك في المكان الصحيح، وستقرأ بضعة أسطر ليسمع المعلم مستواك الحالي.\n\nأخيرًا، حافظ على عادة يومية صغيرة. خمس عشرة دقيقة مركزة من المراجعة يوميًا أفضل من جلسة طويلة مرة أسبوعيًا. الاستمرارية هي المنهج الحقيقي.",
    },
    category: "Guides",
    tags: ["beginners", "online learning"],
    author: "Academy Team",
    status: "published",
    publishedAt: now,
    metaTitle: { en: "How to Start Learning the Quran Online", ar: "كيف تبدأ تعلم القرآن أونلاين" },
    metaDescription: {
      en: "Practical steps to begin online Quran learning: goals, setup, assessment and daily habits.",
      ar: "خطوات عملية لبدء تعلم القرآن أونلاين: الأهداف والتجهيز والتقييم والعادات اليومية.",
    },
    updatedAt: now,
  },
  {
    id: "post_kids_guide",
    slug: "how-to-choose-online-quran-classes-for-children",
    title: { en: "How to Choose Online Quran Classes for Children", ar: "كيف تختار دروس القرآن أونلاين لأطفالك" },
    excerpt: {
      en: "What parents in the UK and Canada should look for: safety, structure, communication, and realistic expectations.",
      ar: "ما الذي يجب أن يبحث عنه أولياء الأمور في بريطانيا وكندا: السلامة والمنهجية والتواصل والتوقعات الواقعية.",
    },
    content: {
      en: "Choosing online Quran classes for your child deserves care. Here is what to look for.\n\nSafety first. Ask how teachers are vetted, who can contact your child, and how lessons are supervised. A serious academy answers these questions clearly and in writing.\n\nStructure second. Look for a defined curriculum with levels, so you can see where your child starts and what comes next — not random lessons each week.\n\nCommunication third. You should receive regular progress updates and have a way to reach the teacher or administration. Learning works best when parents are partners.\n\nFinally, keep expectations realistic. Short, consistent sessions suit young children better than long ones. Ask how the academy handles attention spans, missed lessons, and revision.\n\nBook a free assessment and judge the experience yourself before committing.",
      ar: "اختيار دروس القرآن أونلاين لطفلك يستحق العناية. إليك ما تبحث عنه.\n\nالسلامة أولًا. اسأل عن كيفية اختيار المعلمين، ومن يمكنه التواصل مع طفلك، وكيف تُشرف على الدروس. الأكاديمية الجادة تجيب عن هذه الأسئلة بوضوح وكتابة.\n\nالمنهجية ثانيًا. ابحث عن منهج محدد بمستويات، لترى من أين يبدأ طفلك وما الخطوة التالية — لا دروس عشوائية كل أسبوع.\n\nالتواصل ثالثًا. يجب أن تصلك تحديثات تقدم منتظمة وأن تكون لديك وسيلة للوصول للمعلم أو الإدارة. التعلم ينجح أكثر عندما يكون أولياء الأمور شركاء.\n\nأخيرًا، حافظ على توقعات واقعية. الجلسات القصيرة المنتظمة تناسب الصغار أكثر من الطويلة. اسأل كيف تتعامل الأكاديمية مع مدة الانتباه والدروس الفائتة والمراجعة.\n\nاحجز جلسة تقييم مجانية واحكم على التجربة بنفسك قبل الالتزام.",
    },
    category: "Parents",
    tags: ["children", "safety"],
    author: "Academy Team",
    status: "published",
    publishedAt: now,
    metaTitle: { en: "How to Choose Online Quran Classes for Children", ar: "كيف تختار دروس القرآن أونلاين لأطفالك" },
    metaDescription: {
      en: "A parent's checklist for safe, structured online Quran classes for kids in the UK and Canada.",
      ar: "قائمة تحقق للأهل لاختيار دروس قرآن آمنة ومنظمة للأطفال في بريطانيا وكندا.",
    },
    updatedAt: now,
  },
  {
    id: "post_draft_beginners",
    slug: "online-quran-classes-for-beginners",
    title: { en: "Online Quran Classes for Beginners", ar: "دروس القرآن أونلاين للمبتدئين" },
    excerpt: {
      en: "DRAFT — From the alphabet to your first fluent page: what the beginner journey looks like.",
      ar: "مسودة — من الحروف إلى أول صفحة طليقة: كيف تبدو رحلة المبتدئ.",
    },
    content: {
      en: "DRAFT FOR REVIEW — Outline: alphabet mastery, joining letters, short vowels and sukoon, first words from the Quran, building to a fluent page. Needs academic review before publishing.",
      ar: "مسودة للمراجعة — مخطط: إتقان الحروف، وتركيب الكلمات، والحركات والسكون، وأول كلمات من القرآن، وصولًا لصفحة طليقة. يحتاج مراجعة أكاديمية قبل النشر.",
    },
    category: "Guides",
    tags: ["beginners"],
    author: "Academy Team",
    status: "draft",
    publishedAt: null,
    metaTitle: { en: "Online Quran Classes for Beginners", ar: "دروس القرآن أونلاين للمبتدئين" },
    metaDescription: { en: "Draft under review.", ar: "مسودة قيد المراجعة." },
    updatedAt: now,
  },
  {
    id: "post_draft_recitation",
    slug: "how-to-improve-quran-recitation",
    title: { en: "How to Improve Quran Recitation", ar: "كيف تحسّن تلاوتك للقرآن" },
    excerpt: { en: "DRAFT — Listening, recording, and guided correction cycles.", ar: "مسودة — الاستماع والتسجيل ودورات التصحيح الموجه." },
    content: {
      en: "DRAFT FOR REVIEW — Outline: daily listening habit, recording yourself, one rule at a time, teacher feedback loops. Needs academic review before publishing.",
      ar: "مسودة للمراجعة — مخطط: عادة الاستماع اليومي، وتسجيل النفس، وقاعدة واحدة في كل مرة، وحلقات ملاحظات المعلم. يحتاج مراجعة أكاديمية قبل النشر.",
    },
    category: "Tajweed",
    tags: ["recitation"],
    author: "Academy Team",
    status: "draft",
    publishedAt: null,
    metaTitle: { en: "How to Improve Quran Recitation", ar: "كيف تحسّن تلاوتك للقرآن" },
    metaDescription: { en: "Draft under review.", ar: "مسودة قيد المراجعة." },
    updatedAt: now,
  },
  {
    id: "post_draft_tajweed",
    slug: "understanding-tajweed-for-beginners",
    title: { en: "Understanding Tajweed for Beginners", ar: "فهم التجويد للمبتدئين" },
    excerpt: { en: "DRAFT — What Tajweed is, and the gentle order to learn its rules.", ar: "مسودة — ما هو التجويد، والترتيب المناسب لتعلم قواعده." },
    content: {
      en: "DRAFT FOR REVIEW — Outline: meaning of Tajweed, why it matters, makharij first, then noon/meem rules, then madd. Scholarly review required.",
      ar: "مسودة للمراجعة — مخطط: معنى التجويد وأهميته، والمخارج أولًا، ثم أحكام النون والميم، ثم المد. يتطلب مراجعة علمية.",
    },
    category: "Tajweed",
    tags: ["tajweed", "beginners"],
    author: "Academy Team",
    status: "draft",
    publishedAt: null,
    metaTitle: { en: "Understanding Tajweed for Beginners", ar: "فهم التجويد للمبتدئين" },
    metaDescription: { en: "Draft under review.", ar: "مسودة قيد المراجعة." },
    updatedAt: now,
  },
  {
    id: "post_draft_arabic",
    slug: "learning-arabic-for-quran-understanding",
    title: { en: "Learning Arabic for Quran Understanding", ar: "تعلم العربية لفهم القرآن" },
    excerpt: { en: "DRAFT — How much Arabic you need to start understanding recitation.", ar: "مسودة — كم تحتاج من العربية لتبدأ فهم التلاوة." },
    content: {
      en: "DRAFT FOR REVIEW — Outline: high-frequency Quranic words, basic grammar, root patterns, realistic milestones. Needs academic review before publishing.",
      ar: "مسودة للمراجعة — مخطط: الكلمات القرآنية عالية التكرار، والقواعد الأساسية، وأوزان الجذور، ومراحل واقعية. يحتاج مراجعة أكاديمية قبل النشر.",
    },
    category: "Arabic",
    tags: ["arabic", "quranic arabic"],
    author: "Academy Team",
    status: "draft",
    publishedAt: null,
    metaTitle: { en: "Learning Arabic for Quran Understanding", ar: "تعلم العربية لفهم القرآن" },
    metaDescription: { en: "Draft under review.", ar: "مسودة قيد المراجعة." },
    updatedAt: now,
  },
  {
    id: "post_draft_west",
    slug: "islamic-studies-for-muslim-children-in-the-west",
    title: { en: "Islamic Studies for Muslim Children in the West", ar: "الدراسات الإسلامية لأطفال المسلمين في الغرب" },
    excerpt: { en: "DRAFT — Identity, belonging, and age-appropriate foundations.", ar: "مسودة — الهوية والانتماء والتأسيس المناسب للعمر." },
    content: {
      en: "DRAFT FOR REVIEW — Outline: growing up Muslim in the UK/Canada, belief foundations, Seerah stories, manners, answering hard questions. Needs review before publishing.",
      ar: "مسودة للمراجعة — مخطط: النشأة مسلمًا في بريطانيا/كندا، وأساسيات العقيدة، وقصص السيرة، والآداب، والإجابة عن الأسئلة الصعبة. يحتاج مراجعة قبل النشر.",
    },
    category: "Parents",
    tags: ["children", "identity"],
    author: "Academy Team",
    status: "draft",
    publishedAt: null,
    metaTitle: { en: "Islamic Studies for Muslim Children in the West", ar: "الدراسات الإسلامية لأطفال المسلمين في الغرب" },
    metaDescription: { en: "Draft under review.", ar: "مسودة قيد المراجعة." },
    updatedAt: now,
  },
  {
    id: "post_draft_hifz",
    slug: "a-structured-approach-to-quran-memorization",
    title: { en: "A Structured Approach to Quran Memorization", ar: "منهج منظم لحفظ القرآن" },
    excerpt: { en: "DRAFT — Sabaq, sabqi, manzil: the classic revision system explained.", ar: "مسودة — السبق والسبقي والمنزل: شرح نظام المراجعة التقليدي." },
    content: {
      en: "DRAFT FOR REVIEW — Outline: new lesson method, recent revision, old revision cycles, tracking, rest and sustainability. Scholarly review required.",
      ar: "مسودة للمراجعة — مخطط: طريقة الدرس الجديد، ومراجعة القريب، ودورات مراجعة البعيد، والمتابعة، والراحة والاستدامة. يتطلب مراجعة علمية.",
    },
    category: "Hifz",
    tags: ["memorization"],
    author: "Academy Team",
    status: "draft",
    publishedAt: null,
    metaTitle: { en: "A Structured Approach to Quran Memorization", ar: "منهج منظم لحفظ القرآن" },
    metaDescription: { en: "Draft under review.", ar: "مسودة قيد المراجعة." },
    updatedAt: now,
  },
];

