import type { ServiceDoc } from "./academy";

// Six core services — full bilingual content, unique per service.
// Managed in Admin → Services.

export const seedServices: ServiceDoc[] = [
  {
    id: "svc_quran",
    slug: "quran-classes",
    name: { en: "Online Quran Classes", ar: "دروس القرآن الكريم أونلاين" },
    short: {
      en: "Build stronger Quran reading skills through guided, live lessons tailored to your level.",
      ar: "طوّر مهاراتك في قراءة القرآن من خلال دروس مباشرة موجهة ومناسبة لمستواك.",
    },
    content: {
      en: "Build your Quran reading skills through guided online lessons designed around your current level. Our program supports beginners and continuing learners through structured instruction, practice, and constructive feedback.",
      ar: "طوّر مهاراتك في قراءة القرآن الكريم من خلال دروس أونلاين موجهة ومصممة وفق مستواك الحالي. يدعم البرنامج المبتدئين والطلاب المستمرين عبر التعليم المنظم والتدريب والملاحظات البنّاءة.",
    },
    outcomes: [
      { en: "Read the Quran with clearer pronunciation", ar: "قراءة القرآن بنطق أوضح" },
      { en: "Recognize Arabic letters and their forms", ar: "التعرف على الحروف العربية وأشكالها" },
      { en: "Read with growing fluency", ar: "القراءة بطلاقة متزايدة" },
      { en: "Recite short passages with guidance", ar: "تلاوة مقاطع قصيرة بتوجيه المعلم" },
    ],
    audience: [
      { en: "Beginners starting from the alphabet", ar: "المبتدئون من مستوى الحروف" },
      { en: "Children learning with a parent's support", ar: "الأطفال بمساندة أولياء الأمور" },
      { en: "Adults returning to Quran learning", ar: "الكبار العائدون لتعلم القرآن" },
      { en: "Converts building their first recitation skills", ar: "المسلمون الجدد لبناء مهارات التلاوة الأولى" },
    ],
    curriculum: [
      { en: "Quran reading foundations", ar: "أساسيات قراءة القرآن" },
      { en: "Letter recognition and pronunciation", ar: "التعرف على الحروف ونطقها" },
      { en: "Fluency development", ar: "تطوير الطلاقة في القراءة" },
      { en: "Guided recitation practice", ar: "التدريب الموجه على التلاوة" },
      { en: "Regular learning progress reviews", ar: "مراجعة تقدم الطالب بصورة منتظمة" },
    ],
    icon: "📖",
    order: 1,
    featured: true,
    active: true,
    status: "published",
    metaTitle: { en: "Online Quran Classes for Children & Adults", ar: "دروس القرآن الكريم أونلاين للأطفال والكبار" },
    metaDescription: {
      en: "Guided online Quran classes for beginners, children, adults and converts in the UK and Canada.",
      ar: "دروس قرآن أونلاين موجهة للمبتدئين والأطفال والكبار والمسلمين الجدد في بريطانيا وكندا.",
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: "svc_tajweed",
    slug: "tajweed",
    name: { en: "Tajweed Courses", ar: "دورات التجويد" },
    short: {
      en: "Learn and apply Tajweed rules through structured practice and personalized feedback.",
      ar: "تعلّم قواعد التجويد وطبّقها من خلال التدريب المنظم والمتابعة الشخصية.",
    },
    content: {
      en: "Learn Tajweed through clear explanations and practical recitation exercises. Progress through relevant rules according to your learning level and receive guidance on pronunciation and application. Curriculum details are reviewed and approved by qualified academic staff.",
      ar: "تعلّم قواعد التجويد من خلال شرح واضح وتدريبات عملية على التلاوة. تقدّم في دراسة القواعد المناسبة لمستواك، واحصل على توجيه يساعدك على تحسين النطق والتطبيق. تُراجع تفاصيل المنهج وتُعتمد من كادر أكاديمي مؤهل.",
    },
    outcomes: [
      { en: "Pronounce letters from their correct articulation points", ar: "نطق الحروف من مخارجها الصحيحة" },
      { en: "Apply selected Tajweed rules in recitation", ar: "تطبيق قواعد التجويد المختارة أثناء التلاوة" },
      { en: "Recite with steadier rhythm and control", ar: "التلاوة بإيقاع أكثر ثباتًا وتحكمًا" },
    ],
    audience: [
      { en: "Students who read but want better recitation", ar: "الطلاب الذين يقرؤون ويريدون تحسين التلاوة" },
      { en: "Adults preparing for confident recitation", ar: "الكبار الراغبون في تلاوة واثقة" },
      { en: "Hifz students strengthening their recitation", ar: "طلاب الحفظ الراغبون في تقوية تلاوتهم" },
    ],
    curriculum: [
      { en: "Makharij al-Huruf", ar: "مخارج الحروف" },
      { en: "Selected Tajweed rules by level", ar: "قواعد التجويد المختارة حسب المستوى" },
      { en: "Practical recitation", ar: "التطبيق العملي على التلاوة" },
      { en: "Guided correction", ar: "التصحيح الموجه" },
      { en: "Revision and application", ar: "المراجعة والتطبيق" },
    ],
    icon: "🎙️",
    order: 2,
    featured: true,
    active: true,
    status: "published",
    metaTitle: { en: "Online Tajweed Classes for Better Recitation", ar: "دروس التجويد أونلاين لتحسين التلاوة" },
    metaDescription: {
      en: "Structured online Tajweed instruction with practical recitation and personalized feedback.",
      ar: "تعليم التجويد أونلاين بمنهج منظم وتدريب عملي ومتابعة شخصية.",
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: "svc_hifz",
    slug: "hifz",
    name: { en: "Quran Memorization (Hifz)", ar: "تحفيظ القرآن الكريم" },
    short: {
      en: "Follow a personalized memorization and revision plan designed to support consistency.",
      ar: "اتبع خطة مخصصة لحفظ القرآن ومراجعته، مصممة لدعم الاستمرارية والثبات.",
    },
    content: {
      en: "Build a consistent memorization routine through an individualized plan, guided revision, and regular progress tracking. The program adapts to the learner's age, availability, and current level. We focus on sustainable habits rather than promises of specific completion dates.",
      ar: "أنشئ روتينًا منتظمًا لحفظ القرآن الكريم من خلال خطة فردية ومراجعة موجهة ومتابعة دورية للتقدم. يتكيف البرنامج مع عمر الطالب ووقته المتاح ومستواه الحالي، مع التركيز على العادات المستدامة دون وعود بتواريخ إتمام محددة.",
    },
    outcomes: [
      { en: "Memorize new passages at a sustainable pace", ar: "حفظ مقاطع جديدة بوتيرة مستدامة" },
      { en: "Keep a reliable daily revision routine", ar: "الالتزام بروتين يومي موثوق للمراجعة" },
      { en: "Retain previously memorized portions", ar: "تثبيت المحفوظ السابق" },
    ],
    audience: [
      { en: "Children beginning memorization", ar: "الأطفال في بداية الحفظ" },
      { en: "Adults memorizing alongside work or study", ar: "الكبار الراغبون في الحفظ مع العمل أو الدراسة" },
      { en: "Students resuming an interrupted Hifz journey", ar: "الطلاب المستأنفون لمسيرة حفظ متوقفة" },
    ],
    curriculum: [
      { en: "Individual memorization goals", ar: "أهداف حفظ فردية" },
      { en: "New lesson planning", ar: "تخطيط الدروس الجديدة" },
      { en: "Revision schedules", ar: "جداول المراجعة" },
      { en: "Progress documentation", ar: "توثيق التقدم" },
      { en: "Guidance for consistent practice", ar: "توجيه للممارسة المستمرة" },
    ],
    icon: "🌙",
    order: 3,
    featured: true,
    active: true,
    status: "published",
    metaTitle: { en: "Online Quran Memorization Program (Hifz)", ar: "برنامج تحفيظ القرآن الكريم أونلاين" },
    metaDescription: {
      en: "Personalized Hifz plans with guided revision and progress tracking for children and adults.",
      ar: "خطط حفظ فردية مع مراجعة موجهة ومتابعة للتقدم للأطفال والكبار.",
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: "svc_arabic",
    slug: "arabic",
    name: { en: "Arabic Language Courses", ar: "دورات اللغة العربية" },
    short: {
      en: "Develop Arabic reading, writing, vocabulary, and comprehension for non-native speakers.",
      ar: "طوّر مهارات القراءة والكتابة والمفردات والفهم باللغة العربية لغير الناطقين بها.",
    },
    content: {
      en: "Develop the language skills needed to read, understand, and communicate in Arabic. Choose learning content appropriate to your level, whether you are beginning with the basics or developing existing skills. Separate tracks are available for beginners, Quranic Arabic, children, and adults.",
      ar: "طوّر المهارات اللغوية اللازمة للقراءة والفهم والتواصل باللغة العربية. اختر محتوى تعليميًا مناسبًا لمستواك، سواء كنت تبدأ من الأساسيات أو تعمل على تطوير مهاراتك الحالية. تتوفر مسارات منفصلة للمبتدئين والعربية القرآنية والأطفال والكبار.",
    },
    outcomes: [
      { en: "Read and write the Arabic script confidently", ar: "قراءة النص العربي وكتابته بثقة" },
      { en: "Build everyday and Quranic vocabulary", ar: "بناء مفردات يومية وقرآنية" },
      { en: "Understand basic grammar patterns", ar: "فهم الأنماط النحوية الأساسية" },
      { en: "Follow simple Arabic texts", ar: "متابعة النصوص العربية المبسطة" },
    ],
    audience: [
      { en: "Non-native speakers starting from zero", ar: "غير الناطقين بالعربية من الصفر" },
      { en: "Parents wanting Arabic for their children", ar: "أولياء الأمور الراغبون في تعليم أطفالهم العربية" },
      { en: "Quran students wanting to understand what they recite", ar: "طلاب القرآن الراغبون في فهم ما يتلون" },
    ],
    curriculum: [
      { en: "Arabic alphabet and reading", ar: "الحروف الأبجدية والقراءة" },
      { en: "Writing foundations", ar: "أساسيات الكتابة" },
      { en: "Vocabulary building", ar: "بناء المفردات" },
      { en: "Basic grammar", ar: "القواعد الأساسية" },
      { en: "Quranic Arabic foundations", ar: "أساسيات العربية القرآنية" },
      { en: "Conversation practice in selected tracks", ar: "التدريب على المحادثة في مسارات مختارة" },
    ],
    icon: "🔤",
    order: 4,
    featured: true,
    active: true,
    status: "published",
    metaTitle: { en: "Arabic Language Courses for Non-Native Speakers", ar: "دورات اللغة العربية لغير الناطقين بها" },
    metaDescription: {
      en: "Arabic courses for beginners, children, adults and Quranic Arabic — online and structured.",
      ar: "دورات عربية للمبتدئين والأطفال والكبار والعربية القرآنية — أونلاين ومنظمة.",
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: "svc_islamic",
    slug: "islamic-studies",
    name: { en: "Islamic Studies", ar: "الدراسات الإسلامية" },
    short: {
      en: "Structured lessons in Fiqh, Aqeedah, Seerah, and Islamic ethics per the academy's curriculum.",
      ar: "دروس منظمة في الفقه والعقيدة والسيرة والأخلاق وفق منهج الأكاديمية.",
    },
    content: {
      en: "Explore foundational Islamic knowledge through structured lessons covering selected topics in Fiqh, Aqeedah, Seerah, and Islamic ethics. Content is age-appropriate and aligned with the academy's approved curriculum. Detailed religious rulings follow the academy's defined scholarly review process.",
      ar: "تعرّف على أساسيات المعرفة الإسلامية من خلال دروس منظمة تتناول موضوعات مختارة في الفقه والعقيدة والسيرة والأخلاق الإسلامية. يُراعى في المحتوى ما يناسب العمر، ويُقدّم وفق المنهج المعتمد من الأكاديمية، مع مراجعة علمية للمسائل التفصيلية.",
    },
    outcomes: [
      { en: "Understand foundations of Islamic belief", ar: "فهم أساسيات العقيدة الإسلامية" },
      { en: "Learn key Seerah events and lessons", ar: "تعلم أبرز أحداث السيرة ودروسها" },
      { en: "Apply Islamic manners in daily life", ar: "تطبيق الآداب الإسلامية في الحياة اليومية" },
    ],
    audience: [
      { en: "Children needing age-appropriate foundations", ar: "الأطفال المحتاجون لتأسيس مناسب لأعمارهم" },
      { en: "Converts learning the essentials", ar: "المسلمون الجدد لتعلم الأساسيات" },
      { en: "Adults deepening their knowledge", ar: "الكبار الراغبون في تعميق معارفهم" },
    ],
    curriculum: [
      { en: "Foundations of Islamic belief", ar: "أساسيات العقيدة" },
      { en: "Selected Fiqh topics", ar: "موضوعات فقهية مختارة" },
      { en: "Seerah", ar: "السيرة النبوية" },
      { en: "Islamic manners and ethics", ar: "الآداب والأخلاق الإسلامية" },
      { en: "Practical learning for daily life", ar: "تعلم عملي للحياة اليومية" },
    ],
    icon: "🕌",
    order: 5,
    featured: true,
    active: true,
    status: "published",
    metaTitle: { en: "Online Islamic Studies for Children & Adults", ar: "الدراسات الإسلامية أونلاين للأطفال والكبار" },
    metaDescription: {
      en: "Age-appropriate Islamic Studies lessons in belief, Fiqh, Seerah and ethics.",
      ar: "دروس دراسات إسلامية مناسبة للعمر في العقيدة والفقه والسيرة والأخلاق.",
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: "svc_tafsir",
    slug: "tafsir",
    name: { en: "Quran Understanding & Tafsir", ar: "فهم القرآن والتفسير" },
    short: {
      en: "Explore meanings, context, and lessons of selected passages through guided learning.",
      ar: "تعرّف على معاني الآيات المختارة وسياقها ودروسها من خلال تعلم موجه.",
    },
    content: {
      en: "Explore selected Quranic passages through guided learning focused on meanings, context, vocabulary, and key lessons. Sessions distinguish explanation, interpretation, and areas of scholarly disagreement where relevant, using academically reviewed, reference-based content.",
      ar: "تعرّف على معاني آيات قرآنية مختارة من خلال تعلم موجه يركز على المعاني والسياق والمفردات وأهم الدروس. تُفرّق الجلسات بين الشرح والتفسير ومواضع الاختلاف العلمي عند الحاجة، بمحتوى مراجَع يعتمد على المصادر.",
    },
    outcomes: [
      { en: "Understand vocabulary of selected passages", ar: "فهم مفردات المقاطع المختارة" },
      { en: "Grasp context and key themes", ar: "استيعاب السياق والموضوعات الرئيسية" },
      { en: "Connect lessons to daily life", ar: "ربط الدروس بالحياة اليومية" },
    ],
    audience: [
      { en: "Readers who want to understand recitation", ar: "القراء الراغبون في فهم ما يتلون" },
      { en: "Arabic learners applying their skills", ar: "متعلمو العربية الراغبون في تطبيق مهاراتهم" },
      { en: "Study circles seeking guided discussion", ar: "حلقات الدراسة الباحثة عن نقاش موجه" },
    ],
    curriculum: [
      { en: "Selected Surahs and passages", ar: "سور ومقاطع مختارة" },
      { en: "Vocabulary and meaning", ar: "المفردات والمعاني" },
      { en: "Contextual understanding", ar: "الفهم السياقي" },
      { en: "Key themes", ar: "الموضوعات الرئيسية" },
      { en: "Guided discussion", ar: "نقاش موجه" },
      { en: "Reference-based learning", ar: "تعلم يعتمد على المراجع" },
    ],
    icon: "💡",
    order: 6,
    featured: true,
    active: true,
    status: "published",
    metaTitle: { en: "Quran Understanding & Tafsir Learning", ar: "فهم القرآن الكريم ودروس التفسير" },
    metaDescription: {
      en: "Guided Tafsir learning: meanings, context and lessons of selected Quranic passages.",
      ar: "تعلم التفسير بتوجيه: معاني وسياق ودروس آيات مختارة.",
    },
    updatedAt: new Date().toISOString(),
  },
];

